import "./globals.css";
import { Manrope } from "next/font/google";
import { SessionProvider } from "next-auth/react";

const manrope = Manrope({ subsets: ["latin"], variable: "--Manrope" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>{children}</body>
    </html>
  );
}
