type User {
  username: String!
  name: String!
  email: String!
  phoneNumber: String!
}

type Query {
  users: [User!]!
}

input CreateUser {
  username: String!
  name: String!
  email: String!
  phoneNumber: String!
}

type Mutation {
  createUser(user: CreateUser): User!
}
