type User {
  id: String!
  username: String!
  name: String!
  email: String!
  phoneNumber: String!
  image: String
}

type Query {
  getUser(id: ID!): User!
  getByEmail(email: String!): User!
}

input CreateUser {
  username: String!
  name: String!
  email: String!
  phoneNumber: String!
  password: String!
  image: String
}

type Mutation {
  createUser(user: CreateUser): User!
}
